export const DO_SAVE_PROFILE_IMAGE_REQUEST = 'DO_SAVE_PROFILE_IMAGE_REQUEST';
export const DO_SAVE_PROFILE_IMAGE_IN_PROGRESS = 'DO_SAVE_PROFILE_IMAGE_IN_PROGRESS';
export const DO_SAVE_PROFILE_IMAGE_SUCCESS = 'DO_SAVE_PROFILE_IMAGE_SUCCESS';
export const DO_SAVE_PROFILE_IMAGE_FAILED = 'DO_SAVE_PROFILE_IMAGE_FAILED';
export const UPDATE_PROFILE_IMAGE_FORM = 'UPDATE_PROFILE_IMAGE_FORM';
export const DO_CLEAR_PROFILE_IMAGE = 'DO_CLEAR_PROFILE_IMAGE';
export const DO_UPDATE_PROFILE_IMAGE = 'DO_UPDATE_PROFILE_IMAGE';

export const PERSONAL_DETAILS_TITLE = 'Personal Details';
export const PERSONAL_DETAILS__FORM = 'personalDetailsForm';
export const ACCOUNT_ACCESS_TITLE = 'Account Access';
export const PROFILE_PICTURE_TITLE = 'Profile Picture';
export const DELETE_ACCOUNT_TITLE = 'Delete Account';
export const OTP_CHANGE_FORM = 'OTP_CHANGE_FORM';

export const GET_PERSONAL_DETAILS_REQUEST = 'GET_PERSONAL_DETAILS_REQUEST';
export const GET_PERSONAL_DETAILS_IN_PROGRESS = 'GET_PERSONAL_DETAILS_IN_PROGRESS';
export const GET_PERSONAL_DETAILS_SUCCESS = 'GET_PERSONAL_DETAILS_SUCCESS';
export const GET_PERSONAL_DETAILS_FAILED = 'GET_PERSONAL_DETAILS_FAILED';

export const DO_SAVE_PERSONAL_DETAILS_REQUEST = 'DO_SAVE_PERSONAL_DETAILS_REQUEST';
export const DO_SAVE_PERSONAL_DETAILS_IN_PROGRESS = 'DO_SAVE_PERSONAL_DETAILS_IN_PROGRESS';
export const DO_SAVE_PERSONAL_DETAILS_SUCCESS = 'DO_SAVE_PERSONAL_DETAILS_SUCCESS';
export const DO_SAVE_PERSONAL_DETAILS_FAILED = 'DO_SAVE_PERSONAL_DETAILS_FAILED';

export const DO_UPDATE_USER_PASSWORD_REQUEST = 'DO_UPDATE_USER_PASSWORD_REQUEST';
export const DO_UPDATE_USER_PASSWORD_INPROGRESS = 'DO_UPDATE_USER_PASSWORD_INPROGRESS';
export const DO_UPDATE_USER_PASSWORD_SUCCESS = 'DO_UPDATE_USER_PASSWORD_SUCCESS';
export const DO_UPDATE_USER_PASSWORD_FAILED = 'DO_UPDATE_USER_PASSWORD_FAILED';

export const DO_SAVE_USER_PASSWORD_IN_PROGRESS = 'DO_SAVE_USER_PASSWORD_IN_PROGRESS';
export const CHANGE_PASSWORD_FORM = 'CHANGE_PASSWORD_FORM';
export const DO_UPDATE_UPLOADING_STATE = 'DO_UPDATE_UPLOADING_STATE';

// Scheme user account delete data
export const GET_SCHEME_USER_ACCOUNT_DELETE_DATA_REQUEST = 'getSchemeUserAccountDeleteDataRequest';
export const GET_SCHEME_USER_ACCOUNT_DELETE_DATA_IN_PROGRESS = 'getSchemeUserAccountDeleteDataInProgress';
export const GET_SCHEME_USER_ACCOUNT_DELETE_DATA_SUCCESS = 'getSchemeUserAccountDeleteDataSuccess';
export const GET_SCHEME_USER_ACCOUNT_DELETE_DATA_FAILURE = 'getSchemeUserAccountDeleteDataFailure';

// Send scheme user account delete request
export const SEND_SCHEME_USER_ACCOUNT_DELETE_REQUEST = 'sendSchemeUserAccountDeleteRequest';
export const SEND_SCHEME_USER_ACCOUNT_DELETE_REQUEST_IN_PROGRESS = 'sendSchemeUserAccountDeleteRequestInProgress';
export const SEND_SCHEME_USER_ACCOUNT_DELETE_REQUEST_SUCCESS = 'sendSchemeUserAccountDeleteRequestSuccess';
export const SEND_SCHEME_USER_ACCOUNT_DELETE_REQUEST_FAILURE = 'sendSchemeUserAccountDeleteRequestFailure';
export const VALIDATE_USER_PASSWORD = 'validateUserPass';
export const VALIDATE_USER_PASSWORD_SUCCESS = 'validateUserPasswordSuccess';
export const VALIDATE_USER_PASSWORD_ERROR = 'validateUserPasswordError';

export const DO_OTP_CHANGE_REQUEST = 'DO_OTP_CHANGE_REQUEST';
export const DO_OTP_CHANGE_SUCCESS = 'DO_OTP_CHANGE_SUCCESS';
export const DO_OTP_CHANGE_FAILED = 'DO_OTP_CHANGE_FAILED';

export default {
    PERSONAL_DETAILS_TITLE,
    PERSONAL_DETAILS__FORM,
    GET_PERSONAL_DETAILS_REQUEST,
    GET_PERSONAL_DETAILS_IN_PROGRESS,
    GET_PERSONAL_DETAILS_SUCCESS,
    GET_PERSONAL_DETAILS_FAILED,

    DO_SAVE_PERSONAL_DETAILS_REQUEST,
    DO_SAVE_PERSONAL_DETAILS_IN_PROGRESS,
    DO_SAVE_PERSONAL_DETAILS_SUCCESS,
    DO_SAVE_PERSONAL_DETAILS_FAILED,

    DO_SAVE_USER_PASSWORD_IN_PROGRESS,
    VALIDATE_USER_PASSWORD,
    VALIDATE_USER_PASSWORD_SUCCESS,
    VALIDATE_USER_PASSWORD_ERROR,

    DO_OTP_CHANGE_REQUEST,
    DO_OTP_CHANGE_SUCCESS,
    DO_OTP_CHANGE_FAILED
};
