export const DO_CREATE_SCHEME_REQUEST = 'DO_CREATE_SCHEME_REQUEST';
export const DO_CREATE_SCHEME_IN_PROGRESS = 'DO_CREATE_SCHEME_IN_PROGRESS';
export const DO_CREATE_SCHEME_SUCCESS = 'DO_CREATE_SCHEME_SUCCESS';
export const DO_CREATE_SCHEME_FAILED = 'DO_CREATE_SCHEME_FAILED';

export const GET_SCHEMES_REQUEST = 'GET_SCHEMES_REQUEST';
export const GET_SCHEMES_IN_PROGRESS = 'GET_SCHEMES_IN_PROGRESS';
export const GET_SCHEMES_SUCCESS = 'GET_SCHEMES_SUCCESS';
export const GET_SCHEMES_FAILED = 'GET_SCHEMES_FAILED';

export const GET_SCHEME_REQUEST = 'GET_SCHEME_REQUEST';
export const GET_SCHEME_IN_PROGRESS = 'GET_SCHEME_IN_PROGRESS';
export const GET_SCHEME_SUCCESS = 'GET_SCHEME_SUCCESS';
export const GET_SCHEME_FAILED = 'GET_SCHEME_FAILED';

export const DO_UPDATE_IS_FAVOURITE_REQUEST = 'DO_UPDATE_IS_FAVOURITE_REQUEST';
export const DO_UPDATE_IS_FAVOURITE_IN_PROGRESS = 'DO_UPDATE_IS_FAVOURITE_IN_PROGRESS';
export const DO_UPDATE_IS_FAVOURITE_SUCCESS = 'DO_UPDATE_IS_FAVOURITE_SUCCESS';
export const DO_UPDATE_IS_FAVOURITE_FAILED = 'DO_UPDATE_IS_FAVOURITE_FAILED';

export const DO_UPDATE_SCHEME_FLAG_REQUEST = 'DO_UPDATE_SCHEME_FLAG_REQUEST';
export const DO_UPDATE_SCHEME_FLAG_IN_PROGRESS = 'DO_UPDATE_SCHEME_FLAG_IN_PROGRESS';
export const DO_UPDATE_SCHEME_FLAG_SUCCESS = 'DO_UPDATE_SCHEME_FLAG_SUCCESS';
export const DO_UPDATE_SCHEME_FLAG_FAILED = 'DO_UPDATE_SCHEME_FLAG_FAILED';

export const GET_TASK_MANAGER_TASKS = 'GET_TASK_MANAGER_TASKS';
export const GET_TASK_MANAGER_TASKS_SUCCESS = 'GET_TASK_MANAGER_TASKS_SUCCESS';
export const GET_TASK_MANAGER_TASKS_FAILED = 'GET_TASK_MANAGER_TASKS_FAILED';
export const GET_TASK_MANAGER_COUNT = 'GET_TASK_MANAGER_COUNT';
export const GET_TASK_MANAGER_COUNT_SUCCESS = 'GET_TASK_MANAGER_COUNT_SUCCESS';
export const GET_TASK_MANAGER_COUNT_FAIL = 'GET_TASK_MANAGER_COUNT_FAIL';

export default {
    DO_CREATE_SCHEME_REQUEST,
    DO_CREATE_SCHEME_IN_PROGRESS,
    DO_CREATE_SCHEME_SUCCESS,
    DO_CREATE_SCHEME_FAILED,

    GET_SCHEMES_REQUEST,
    GET_SCHEMES_IN_PROGRESS,
    GET_SCHEMES_SUCCESS,
    GET_SCHEMES_FAILED,

    GET_SCHEME_REQUEST,
    GET_SCHEME_IN_PROGRESS,
    GET_SCHEME_SUCCESS,
    GET_SCHEME_FAILED,

    DO_UPDATE_IS_FAVOURITE_REQUEST,
    DO_UPDATE_IS_FAVOURITE_IN_PROGRESS,
    DO_UPDATE_IS_FAVOURITE_SUCCESS,
    DO_UPDATE_IS_FAVOURITE_FAILED,

    DO_UPDATE_SCHEME_FLAG_REQUEST,
    DO_UPDATE_SCHEME_FLAG_IN_PROGRESS,
    DO_UPDATE_SCHEME_FLAG_SUCCESS,
    DO_UPDATE_SCHEME_FLAG_FAILED,

    GET_TASK_MANAGER_TASKS,
    GET_TASK_MANAGER_TASKS_SUCCESS,
    GET_TASK_MANAGER_TASKS_FAILED,
    GET_TASK_MANAGER_COUNT,
    GET_TASK_MANAGER_COUNT_SUCCESS,
    GET_TASK_MANAGER_COUNT_FAIL
};
