export const DO_CONTACT_US_REQUEST = 'DO_CONTACT_US_REQUEST';
export const DO_CONTACT_US_IN_PROGRESS = 'DO_CONTACT_US_IN_PROGRESS';
export const DO_CONTACT_US_SUCCESS = 'DO_CONTACT_US_SUCCESS';
export const DO_CONTACT_US_FAILED = 'DO_CONTACT_US_FAILED';

export default {
    DO_CONTACT_US_REQUEST,
    DO_CONTACT_US_IN_PROGRESS,
    DO_CONTACT_US_SUCCESS,
    DO_CONTACT_US_FAILED
};
