export const GET_SIGN_URL_IN_PROGRESS = 'GET_SIGN_URL_IN_PROGRESS';
export const GET_SIGN_URL_SUCCESS = 'GET_SIGN_URL_SUCCESS';

export const UPLOAD_TO_S3_BUCKET_IN_PROGRESS = 'UPLOAD_TO_S3_BUCKET_IN_PROGRESS';
export const UPLOAD_TO_S3_BUCKET_SUCCESS = 'UPLOAD_TO_S3_BUCKET_SUCCESS';

export const GET_GENERATED_URL_IN_PROGRESS = 'GET_GENERATED_URL_IN_PROGRESS';
export const GET_GENERATED_URL_SUCCESS = 'GET_GENERATED_URL_SUCCESS';
