/*
ACTIVATION TYPES

you need to use these constants to define which type of activation screen you need to create
*/
const ACTIVATION_TYPE_DEFAULT = 'ACTIVATION_TYPE_DEFAULT';
const ACTIVATION_TYPE_USING_FORM = 'ACTIVATION_TYPE_USING_FORM';
const ACTIVATION_TYPE_USING_FORM_TABS = 'ACTIVATION_TYPE_USING_FORM_TABS';

export { ACTIVATION_TYPE_DEFAULT, ACTIVATION_TYPE_USING_FORM, ACTIVATION_TYPE_USING_FORM_TABS };
