const APPROVE_REJECT_TYPE_SIMPLE = 'APPROVE_REJECT_TYPE_SIMPLE';
const APPROVE_REJECT_TYPE_TABS = 'APPROVE_REJECT_TYPE_TABS';
const MULTICLIENT_APPROVE_REJECT_TYPE_SIMPLE = 'MULTICLIENT_APPROVE_REJECT_TYPE_SIMPLE';
const APPROVE_REJECT_CONFIRM_COMMENT_FORM = 'APPROVE_REJECT_CONFIRM_COMMENT_FORM';
const CONTENT_POSITION_CENTER = 'CENTER';
const CONTENT_POSITION_TOP = 'TOP';
export {
    APPROVE_REJECT_TYPE_SIMPLE,
    APPROVE_REJECT_TYPE_TABS,
    MULTICLIENT_APPROVE_REJECT_TYPE_SIMPLE,
    APPROVE_REJECT_CONFIRM_COMMENT_FORM,
    CONTENT_POSITION_CENTER,
    CONTENT_POSITION_TOP
};
