/**
 * DOWNLOADER TYPES
 *
 * if you need to create a new download feature, you can create a new downloader for it
 */
const DOWNLOAD_USING_DOCUMENT_LINK = 'DOWNLOAD_USING_DOCUMENT_LINK';
const DOWNLOAD_FORM_DATA_ZIP_TYPE_TABS = 'DOWNLOAD_FORM_DATA_ZIP_TYPE_TABS';
const DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE = 'DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE';
const DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE_WITH_DATA_CHANGE = 'DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE_WITH_DATA_CHANGE';
export {
    DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE,
    DOWNLOAD_FORM_DATA_ZIP_TYPE_SIMPLE_WITH_DATA_CHANGE,
    DOWNLOAD_USING_DOCUMENT_LINK,
    DOWNLOAD_FORM_DATA_ZIP_TYPE_TABS
};
