const APPROVERS_SELECTION = 'APP_SL';
const SIGNATORIES_SELECTION = 'SIG_SL';

const DEFAULT_USER_PICKER = 'DEFAULT_USER_PICKER';
const TRUSTEE_USER_PICKER = 'TRUSTEE_USER_PICKER';

export { APPROVERS_SELECTION, SIGNATORIES_SELECTION, DEFAULT_USER_PICKER, TRUSTEE_USER_PICKER };
