const GENERATE_PUBLISH_TYPE_UPLOAD = 'GENERATE_PUBLISH_TYPE_UPLOAD';
const GENERATE_PUBLISH_TYPE_UPLOAD_TAB = 'GENERATE_PUBLISH_TYPE_UPLOAD_TAB';
const GENERATE_PUBLISH_TYPE_SINGLE = 'GENERATE_PUBLISH_TYPE_SINGLE';
const GENERATE_PUBLISH_TYPE_MANDATE = 'GENERATE_PUBLISH_TYPE_MANDATE';
const GENERATE_PUBLISH_TYPE_MULTIPLE = 'GENERATE_PUBLISH_TYPE_MULTIPLE';
const GENERATE_PUBLISH_TYPE_FORM = 'GENERATE_PUBLISH_TYPE_FORM';
const GENERATE_PUBLISH_TYPE_PROPOSAL = 'GENERATE_PUBLISH_TYPE_PROPOSAL';
const GENERATE_PUBLISH_TYPE_PROPOSAL_WITH_TABS = 'GENERATE_PUBLISH_TYPE_PROPOSAL_WITH_TABS';
const GENERATE_PUBLISH_TYPE_SCHEME = 'GENERATE_PUBLISH_TYPE_SCHEME';
const GENERATE_PUBLISH_TYPE_MULTICLIENT = 'GENERATE_PUBLISH_TYPE_MULTICLIENT';

const PUBLISH_INITIAL_CLAIM = 'publish';
const DOCUMENT_STATUS_GENERATED = 'DOC_GEN';
const DOCUMENT_STATUS_PUBLISHED = 'DOC_PUB';
const DOCUMENT_STATUS_PUBLISH = 'PUBLISHED';

export {
    GENERATE_PUBLISH_TYPE_UPLOAD,
    GENERATE_PUBLISH_TYPE_UPLOAD_TAB,
    GENERATE_PUBLISH_TYPE_SINGLE,
    GENERATE_PUBLISH_TYPE_MULTIPLE,
    GENERATE_PUBLISH_TYPE_FORM,
    GENERATE_PUBLISH_TYPE_PROPOSAL,
    GENERATE_PUBLISH_TYPE_SCHEME,
    GENERATE_PUBLISH_TYPE_MULTICLIENT,
    GENERATE_PUBLISH_TYPE_MANDATE,
    PUBLISH_INITIAL_CLAIM,
    GENERATE_PUBLISH_TYPE_PROPOSAL_WITH_TABS,
    DOCUMENT_STATUS_GENERATED,
    DOCUMENT_STATUS_PUBLISHED,
    DOCUMENT_STATUS_PUBLISH
};
