/**
 * REDUX CONSTANTS
 *
 */
const GET_SCHEME_WORKFLOWS_REQUEST = 'GET_SCHEME_WORKFLOWS_REQUEST';
const GET_SCHEME_WORKFLOWS_SUCCESS = 'GET_SCHEME_WORKFLOWS_SUCCESS';
const GET_SCHEME_WORKFLOWS_FAILED = 'GET_SCHEME_WORKFLOWS_FAILED';
const GET_SCHEME_WORKFLOWS_INPROGRESS = 'GET_SCHEME_WORKFLOWS_INPROGRESS';

const UPDATE_WORKFLOW_STEP_REQUEST = 'UPDATE_WORKFLOW_STEP_REQUEST';
const UPDATE_WORKFLOW_STEP_IN_PROGRESS = 'UPDATE_WORKFLOW_STEP_IN_PROGRESS';
const UPDATE_WORKFLOW_STEP_SUCCESS = 'UPDATE_WORKFLOW_STEP_SUCCESS';
const UPDATE_WORKFLOW_STEP_ERROR = 'UPDATE_WORKFLOW_STEP_ERROR';

const GET_WORKFLOW_STEP_REQUEST = 'GET_WORKFLOW_STEP_REQUEST';
const GET_WORKFLOW_STEP_IN_PROGRESS = 'GET_WORKFLOW_STEP_IN_PROGRESS';
const GET_WORKFLOW_STEP_SUCCESS = 'GET_WORKFLOW_STEP_SUCCESS';
const GET_WORKFLOW_STEP_ERROR = 'GET_WORKFLOW_STEP_ERROR';

const GET_ASSIGN_USER_LIST = 'GET_ASSIGN_USER_LIST';
const GET_ASSIGN_USER_LIST_IN_PROGRESS = 'GET_ASSIGN_USER_LIST_IN_PROGRESS';
const GET_ASSIGN_USER_LIST_SUCCESS = 'GET_ASSIGN_USER_LIST_SUCCESS';
const GET_ASSIGN_USER_LIST_FAILED = 'GET_ASSIGN_USER_LIST_FAILED';

const UPDATE_ASSIGN_USER_REQUEST = 'UPDATE_ASSIGN_USER_REQUEST';
const UPDATE_ASSIGN_USER_IN_PROGRESS = 'UPDATE_ASSIGN_USER_IN_PROGRESS';
const UPDATE_ASSIGN_USER_SUCCESS = 'UPDATE_ASSIGN_USER_SUCCESS';
const UPDATE_ASSIGN_USER_ERROR = 'UPDATE_ASSIGN_USER_ERROR';

const GET_ASSIGNED_USER_REQUEST = 'GET_ASSIGNED_USER_REQUEST';
const GET_ASSIGNED_USER_IN_PROGRESS = 'GET_ASSIGNED_USER_IN_PROGRESS';
const GET_ASSIGNED_USER_SUCCESS = 'GET_ASSIGNED_USER_SUCCESS';
const GET_ASSIGNED_USER_ERROR = 'GET_ASSIGNED_USER_ERROR';

const REQUEST_ABORT = 'REQUEST_ABORT';
const REQUEST_ABORT_IN_PROGRESS = 'REQUEST_ABORT_IN_PROGRESS';
const REQUEST_ABORT_SUCCESS = 'REQUEST_ABORT_SUCCESS';
const REQUEST_ABORT_ERROR = 'REQUEST_ABORT_ERROR';

const REQUEST_ABORT_WORKFLOWS = 'REQUEST_ABORT_WORKFLOWS';
const REQUEST_ABORT_WORKFLOWS_IN_PROGRESS = 'REQUEST_ABORT_WORKFLOWS_IN_PROGRESS';
const REQUEST_ABORT_WORKFLOWS_SUCCESS = 'REQUEST_ABORT_WORKFLOWS_SUCCESS';
const REQUEST_ABORT_WORKFLOWS_ERROR = 'REQUEST_ABORT_WORKFLOWS_ERROR';

const INTERNAL_STEP_ACTION_IN_PROGRESS = 'INTERNAL_STEP_ACTION_IN_PROGRESS';

const REQUEST_GET_OUTPUT_FILES = 'REQUEST_GET_OUTPUT_FILES';
const REQUEST_GET_OUTPUT_FILES_IN_PROGRESS = 'REQUEST_GET_OUTPUT_FILES_IN_PROGRESS';
const REQUEST_GET_OUTPUT_FILES_SUCCESS = 'REQUEST_GET_OUTPUT_FILES_SUCCESS';
const REQUEST_GET_OUTPUT_FILES_ERROR = 'REQUEST_GET_OUTPUT_FILES_ERROR';

export {
    GET_SCHEME_WORKFLOWS_REQUEST,
    GET_SCHEME_WORKFLOWS_SUCCESS,
    GET_SCHEME_WORKFLOWS_FAILED,
    GET_SCHEME_WORKFLOWS_INPROGRESS,
    UPDATE_WORKFLOW_STEP_REQUEST,
    UPDATE_WORKFLOW_STEP_IN_PROGRESS,
    UPDATE_WORKFLOW_STEP_SUCCESS,
    UPDATE_WORKFLOW_STEP_ERROR,
    GET_WORKFLOW_STEP_REQUEST,
    GET_WORKFLOW_STEP_IN_PROGRESS,
    GET_WORKFLOW_STEP_SUCCESS,
    GET_WORKFLOW_STEP_ERROR,
    GET_ASSIGN_USER_LIST,
    GET_ASSIGN_USER_LIST_IN_PROGRESS,
    GET_ASSIGN_USER_LIST_SUCCESS,
    GET_ASSIGN_USER_LIST_FAILED,
    UPDATE_ASSIGN_USER_REQUEST,
    UPDATE_ASSIGN_USER_IN_PROGRESS,
    UPDATE_ASSIGN_USER_SUCCESS,
    UPDATE_ASSIGN_USER_ERROR,
    GET_ASSIGNED_USER_REQUEST,
    GET_ASSIGNED_USER_IN_PROGRESS,
    GET_ASSIGNED_USER_SUCCESS,
    GET_ASSIGNED_USER_ERROR,
    REQUEST_ABORT,
    REQUEST_ABORT_IN_PROGRESS,
    REQUEST_ABORT_SUCCESS,
    REQUEST_ABORT_ERROR,
    REQUEST_ABORT_WORKFLOWS,
    REQUEST_ABORT_WORKFLOWS_IN_PROGRESS,
    REQUEST_ABORT_WORKFLOWS_SUCCESS,
    REQUEST_ABORT_WORKFLOWS_ERROR,
    INTERNAL_STEP_ACTION_IN_PROGRESS,
    REQUEST_GET_OUTPUT_FILES,
    REQUEST_GET_OUTPUT_FILES_IN_PROGRESS,
    REQUEST_GET_OUTPUT_FILES_SUCCESS,
    REQUEST_GET_OUTPUT_FILES_ERROR
};
