const UPLOAD_SELECT_TYPE_SINGLE_PAGE = 'UPLOAD_SELECT_TYPE_SINGLE_PAGE';
const UPLOAD_SELECT_TYPE_SIMPLE = 'UPLOAD_SELECT_TYPE_SIMPLE';
const UPLOAD_SELECT_TYPE_WITH_CHILDREN = 'UPLOAD_SELECT_TYPE_WITH_CHILDREN';

export { UPLOAD_SELECT_TYPE_SINGLE_PAGE, UPLOAD_SELECT_TYPE_SIMPLE, UPLOAD_SELECT_TYPE_WITH_CHILDREN };
