export const GET_AUDIT_TRAIL_DATA_REQUEST = 'GET_AUDIT_TRAIL_DATA_REQUEST';
export const GET_AUDIT_TRAIL_DATA_INPROGRESS = 'GET_AUDIT_TRAIL_DATA_INPROGRESS';
export const GET_AUDIT_TRAIL_DATA_SUCCESS = 'GET_AUDIT_TRAIL_DATA_SUCCESS';
export const GET_AUDIT_TRAIL_DATA_FAILED = 'GET_AUDIT_TRAIL_DATA_FAILED';
