export const ADD_USER_FORM = 'AddUserForm';

export const GET_CONTRIBUTORS_REQUEST = 'GET_CONTRIBUTORS_REQUEST';
export const GET_CONTRIBUTORS_IN_PROGRESS = 'GET_CONTRIBUTORS_IN_PROGRESS';
export const GET_CONTRIBUTORS_SUCCESS = 'GET_CONTRIBUTORS_SUCCESS';
export const GET_CONTRIBUTORS_FAILED = 'GET_CONTRIBUTORS_FAILED';

export const ADD_CONTRIBUTORS_REQUEST = 'ADD_CONTRIBUTORS_REQUEST';
export const ADD_CONTRIBUTORS_IN_PROGRESS = 'ADD_CONTRIBUTORS_IN_PROGRESS';
export const ADD_CONTRIBUTORS_SUCCESS = 'ADD_CONTRIBUTORS_SUCCESS';
export const ADD_CONTRIBUTORS_FAILED = 'ADD_CONTRIBUTORS_FAILED';

export const GET_USER_GROUPS_REQUEST = 'GET_USER_GROUPS_REQUEST';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_FAILED = 'GET_USER_GROUPS_FAILED';

export const SAVE_USER_GROUPS_REQUEST = 'SAVE_USER_GROUPS_REQUEST';
export const SAVE_USER_GROUPS_SUCCESS = 'SAVE_USER_GROUPS_SUCCESS';
export const SAVE_USER_GROUPS_FAILED = 'SAVE_USER_GROUPS_FAILED';

export const DELETE_GROUPS_REQUEST = 'DELETE_GROUPS_REQUEST';
export const DELETE_GROUPS_SUCCESS = 'DELETE_GROUPS_SUCCESS';
export const DELETE_GROUPS_FAILED = 'DELETE_GROUPS_FAILED';

export const GET_USER_CLAIMS_REQUEST = 'GET_USER_CLAIMS_REQUEST';
export const GET_USER_CLAIMS_SUCCESS = 'GET_USER_CLAIMS_SUCCESS';
export const GET_USER_CLAIMS_FAILED = 'GET_USER_CLAIMS_FAILED';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';

export const GET_FN_N_LN_BY_EMAIL_REQUEST = 'GET_FN_N_LN_BY_EMAIL_REQUEST';
export const GET_FN_N_LN_BY_EMAIL_SUCCESS = 'GET_FN_N_LN_BY_EMAIL_SUCCESS';
export const GET_FN_N_LN_BY_EMAIL_FAILED = 'GET_FN_N_LN_BY_EMAIL_FAILED';

export const GET_USER_GROUPS_BY_ID = 'GET_USER_GROUPS_BY_ID';
export const GET_USER_GROUPS_BY_ID_SUCCESS = 'GET_USER_GROUPS_BY_ID_SUCCESS';
export const GET_USER_GROUPS_BY_ID_FAILED = 'GET_USER_GROUPS_BY_ID_FAILED';

export const GET_CONTRIBUTOR_BY_ID_REQUEST = 'GET_CONTRIBUTOR_BY_ID_REQUEST';
export const GET_CONTRIBUTOR_BY_ID_SUCCESS = 'GET_CONTRIBUTOR_BY_ID_SUCCESS';
export const GET_CONTRIBUTOR_BY_ID_FAILED = 'GET_CONTRIBUTOR_BY_ID_FAILED';

export const GET_LOGGED_USER_CLAIMS = 'GET_LOGGED_USER_CLAIMS';
export const GET_LOGGED_USER_CLAIMS_IN_PROGRESS = 'GET_LOGGED_USER_CLAIMS_IN_PROGRESS';
export const GET_LOGGED_USER_CLAIMS_SUCCESS = 'GET_LOGGED_USER_CLAIMS_SUCCESS';
export const GET_LOGGED_USER_CLAIMS_FAILED = 'GET_LOGGED_USER_CLAIMS_FAILED';

export const ADD_CLAIMS_GROUP_FORM = 'AddClaimsGroupForm';

export const ADD_SCHEME_USERS = 'addSchemeUsers';
export const EDIT_SCHEME_USERS = 'editSchemeUsers';
export const ADD_SCHEME_GROUPS = 'addSchemeGroups';
export const MODIFY_SCHEME_GROUPS = 'modifySchemeGroups';
export const EDIT_OTP_PHONE_NUMBER = 'editOtp';

export const REMOVE_SCHEME_USER_FROM_SCHEME_REQUEST = 'removeSchemeUserFromSchemeRequest';
export const REMOVE_SCHEME_USER_FROM_SCHEME_SUCCESS = 'removeSchemeUserFromSchemeSuccess';
export const REMOVE_SCHEME_USER_FROM_SCHEME_FAILURE = 'removeSchemeUserFromSchemeFailure';

export const REMOVE_SCHEME_USER_ALERTS_SYSTEM_MESSAGES = {
    CONFIRMATION_MODAL_TITLE: 'Do you want to remove this scheme user from the scheme?',
    CONFIRMATION_MODAL_CONTENT: 'This scheme user will lose access to the scheme along with any permissions.',
    REQUEST_SUCCESS: 'Successfully removed the scheme user from scheme.',
    REQUEST_FAILURE: 'Error occured attempting to remove the scheme user from scheme.'
};

export const TEMP_REMOVE_SCHEME_USER_CLAIM = 'cl-um-1';
export const SELECT_AT_LEAST_ONE_NOTI_AND_CLAIM =
    'Please select at least one permission and one notification to set up a group.';
