/**
 * ACTIONS
 *
 */
const DATA_SAVE_ACTION = 'DATA_SAVE_ACTION';
const SUBMIT_ACTION = 'SUBMIT_ACTION';
const ACTIVE_MANDATE_ACTION = 'ACTIVE_MANDATE_ACTION';
const DEACTIVATE_ACTION = 'DEACTIVATE_ACTION';

/**
 * BUTTON TITLES
 *
 */
const BUTTON_TITLE_SAVE = 'save';
const BUTTON_TITLE_REQUEST = 'request';
const BUTTON_TITLE_REQUEST_ADVICE = 'request advice';
const BUTTON_TITLE_DOWNLOAD = 'download';
const BUTTON_TITLE_CONTINUE = 'continue';
const BUTTON_TITLE_UPDATE = 'update';
const BUTTON_TITLE_SUBMIT = 'submit';

/**
 * DEFAULT MESSAGES
 *
 */
const ON_SUBMIT_MESSAGE = 'Successfully submitted.';
const PROPOSAL_REQUESTED = 'Proposal requested.';
const REQUEST_IAA_DATA_REQUEST_SUCCESS = 'Request submitted.';
const REQUEST_REQAMAO_REQUEST_SUCCESS = 'Your account has been requested.';
const SIGN_CONTINUE_REQUEST_SUCCESS = 'Data saved successfully.';
const ON_SAVE_MESSAGE = 'Information saved.';
const ON_ACTIVATE_MESSAGE = 'Account activated.';

export {
    DATA_SAVE_ACTION,
    SUBMIT_ACTION,
    ACTIVE_MANDATE_ACTION,
    DEACTIVATE_ACTION,
    BUTTON_TITLE_SAVE,
    BUTTON_TITLE_REQUEST,
    BUTTON_TITLE_REQUEST_ADVICE,
    BUTTON_TITLE_SUBMIT,
    BUTTON_TITLE_DOWNLOAD,
    BUTTON_TITLE_CONTINUE,
    BUTTON_TITLE_UPDATE,
    ON_SUBMIT_MESSAGE,
    ON_SAVE_MESSAGE,
    ON_ACTIVATE_MESSAGE,
    PROPOSAL_REQUESTED,
    REQUEST_IAA_DATA_REQUEST_SUCCESS,
    REQUEST_REQAMAO_REQUEST_SUCCESS,
    SIGN_CONTINUE_REQUEST_SUCCESS
};
