const APPROVERS_SELECTION = 'APP_SL';
const SIGNATORIES_SELECTION = 'SIG_SL';

const PICK_USER_TYPE_SIMPLE = 'PICK_USER_TYPE_SIMPLE';
const PICK_USER_TYPE_CATEGORY = 'PICK_USER_TYPE_CATEGORY';

const SINGLE_CATEGORY = 'SINGLE_CATEGORY';
const CATEGORY_WITH_SUB_CATEGORIES = 'CATEGORY_WITH_SUB_CATEGORIES';

export {
    APPROVERS_SELECTION,
    SIGNATORIES_SELECTION,
    PICK_USER_TYPE_SIMPLE,
    PICK_USER_TYPE_CATEGORY,
    SINGLE_CATEGORY,
    CATEGORY_WITH_SUB_CATEGORIES
};
