export const UPDATE_REPORT_DATA = 'UPDATE_REPORT_DATA';
export const UPDATE_REPORT_DATA_SUCCESS = 'UPDATE_REPORT_DATA_SUCCESS';
export const UPDATE_REPORT_DATA_ERROR = 'UPDATE_REPORT_DATA_ERROR';

export const GET_STEP_DATA = 'GET_STEP_DATA';
export const GET_STEP_DATA_SUCCESS = 'GET_STEP_DATA_SUCCESS';
export const GET_STEP_DATA_ERROR = 'GET_STEP_DATA_ERROR';

export const UPLOAD_REPORT = 'UPLOAD_REPORT';
export const UPLOAD_REPORT_SUCCESS = 'UPLOAD_REPORT_SUCCESS';

export const DOWNLOAD_REPORT = 'DOWNLOAD_REPORT';
export const DOWNLOAD_REPORT_SUCCESS = 'DOWNLOAD_REPORT_SUCCESS';

export const RA_PROCEED = 'RA_PROCEED';
export const RA_REPORT_UPLOAD = 'RA_REPORT_UPLOAD';
export const RA_UPLOAD_PROCEED = 'RA_UPLOAD_PROCEED';
export const RA_DATA_CHANGE = 'RA_DATA_CHANGE';
export const RA_REPORT_AUTHORIZE = 'RA_REPORT_AUTHORIZE';
export const RA_REPORT_DELETE = 'RA_REPORT_DELETE';
export const RA_NOTIFY_REPORT = 'RA_NOTIFY_REPORT';
export const RA_PUBLISH = 'RA_PUBLISH';
export const RA_COMMENT = 'RA_COMMENT';

export const TableHandlers = {
    VIEW: 'VIEW',
    UPLOAD: 'UPLOAD',
    DOWNLOAD: 'DOWNLOAD',
    DELETE: 'DELETE',
    APPROVE_REJECT: 'APPROVE_REJECT'
};
