export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const MARK_AS_READ_REQUEST = 'MARK_AS_READ_REQUEST';
export const MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS';
export const MARK_AS_READ_ERROR = 'MARK_AS_READ_ERROR';

export const GET_SCHEMES_LIST_BY_USER_REQUEST = 'GET_SCHEMES_LIST_BY_USER_REQUEST';
export const GET_SCHEMES_LIST_BY_USER_SUCCESS = 'GET_SCHEMES_LIST_BY_USER_SUCCESS';
export const GET_SCHEMES_LIST_BY_USER_ERROR = 'GET_SCHEMES_LIST_BY_USER_ERROR';

export const GET_SCHEME_USER_LIST_REQUEST = 'GET_SCHEME_USER_LIST_REQUEST';
export const GET_SCHEME_USER_LIST_SUCCESS = 'GET_SCHEME_USER_LIST_SUCCESS';
export const GET_SCHEME_USER_LIST_ERROR = 'GET_SCHEME_USER_LIST_ERROR';

export const GET_LGIM_USER_LIST_REQUEST = 'GET_LGIM_USER_LIST_REQUEST';
export const GET_LGIM_USER_LIST_SUCCESS = 'GET_LGIM_USER_LIST_SUCCESS';
export const GET_LGIM_USER_LIST_ERROR = 'GET_LGIM_USER_LIST_ERROR';

export const SET_TASK_EMAIL_CONFIG_REQUEST = 'SET_TASK_EMAIL_CONFIG_REQUEST';
export const SET_TASK_EMAIL_CONFIG_SUCCESS = 'SET_TASK_EMAIL_CONFIG_SUCCESS';
export const SET_TASK_EMAIL_CONFIG_ERROR = 'SET_TASK_EMAIL_CONFIG_ERROR';

export const GET_TASK_EMAIL_CONFIG_REQUEST = 'GET_TASK_EMAIL_CONFIG_REQUEST';
export const GET_TASK_EMAIL_CONFIG_SUCCESS = 'GET_TASK_EMAIL_CONFIG_SUCCESS';
export const GET_TASK_EMAIL_CONFIG_ERROR = 'GET_TASK_EMAIL_CONFIG_ERROR';

export const RESET_ASSIGNEE_LIST = 'RESET_ASSIGNEE_LIST';
export const RESET_SCHEME_LIST = 'RESET_SCHEME_LIST';
