export const DO_GET_INITIAL_VALUES = 'DO_GET_INITIAL_VALUES';
export const DO_GET_INITIAL_VALUES_INPROGRESS = 'DO_GET_INITIAL_VALUES_INPROGRESS';
export const DO_GET_INITIAL_VALUES_SUCCESS = 'DO_GET_INITIAL_VALUES_SUCCESS';
export const DO_GET_INITIAL_VALUES_FAIL = 'DO_GET_INITIAL_VALUES_FAIL';

export const DO_REJECT_INITIAL_PROPOSAL = 'DO_REJECT_INITIAL_PROPOSAL';
export const DO_REJECT_INITIAL_PROPOSAL_INPROGRESS = 'DO_REJECT_INITIAL_PROPOSAL_INPROGRESS';
export const DO_REJECT_INITIAL_PROPOSAL_SUCCESS = 'DO_REJECT_INITIAL_PROPOSAL_SUCCESS';
export const DO_REJECT_INITIAL_PROPOSAL_FAIL = 'DO_REJECT_INITIAL_PROPOSAL_FAIL';

export const PA_ANALYZE_REQUEST = 'PA_ANALYZE_REQUEST';
export const PA_ANALYZE_IN_PROGRESS = 'PA_ANALYZE_IN_PROGRESS';
export const PA_ANALYZE_SUCCESS = 'PA_ANALYZE_SUCCESS';
export const PA_ANALYZE_ERROR = 'PA_ANALYZE_ERROR';

export const PA_ANALYZE_REQUEST_ABORT = 'PA_ANALYZE_REQUEST_ABORT';

export const PA_ANALYZE_ERROR_ABORT = 'PA_ANALYZE_ERROR_ABORT';
export const PA_REJECT_WARNING_MESSAGE =
    'Are you sure you want to reject the formal proposal and use the new target return?';
export const PA_REJECT_WARNING_MESSAGE_TITLE = 'Warning';
export const INVALID_TARGET_RETURN_MESSAGE = 'Invalid target return value.';
export const REJECT_DISABLED_TARGET_RETURN_CHANGED_ERROR_MESSAGE =
    'Please analyze the new target return you selected prior to rejecting the document(s).';
export const EXECUTION_ERROR = 'Something went wrong.';
export const PORTFOLIO_FORM = 'PORTFOLIO_FORM';
export const SET_INITIAL_VALUES = 'SET_INITIAL_VALUES';

export const PA_AVAILABLE_WORKFLOW_STEPS = {
    REVIEW_PROPOSAL: 'revip',
    REVIEW_ADVISOR_REPORT: 'revar',
    REVIEW_FMC: 'revfma',
    REVIEW_PMC: 'revpmc'
};

export default {
    DO_GET_INITIAL_VALUES,
    DO_GET_INITIAL_VALUES_INPROGRESS,
    DO_GET_INITIAL_VALUES_SUCCESS,
    DO_GET_INITIAL_VALUES_FAIL,

    DO_REJECT_INITIAL_PROPOSAL,
    DO_REJECT_INITIAL_PROPOSAL_INPROGRESS,
    DO_REJECT_INITIAL_PROPOSAL_SUCCESS,
    DO_REJECT_INITIAL_PROPOSAL_FAIL,

    PA_ANALYZE_REQUEST,
    PA_ANALYZE_IN_PROGRESS,
    PA_ANALYZE_SUCCESS,
    PA_ANALYZE_ERROR,

    PA_ANALYZE_REQUEST_ABORT,

    PA_ANALYZE_ERROR_ABORT,

    PA_AVAILABLE_WORKFLOW_STEPS,
    PA_REJECT_WARNING_MESSAGE,
    PA_REJECT_WARNING_MESSAGE_TITLE,
    INVALID_TARGET_RETURN_MESSAGE,
    EXECUTION_ERROR,
    PORTFOLIO_FORM
};
