export const DO_LOGIN_REQUEST = 'DO_LOGIN_REQUEST';
export const DO_LOGIN_IN_PROGRESS = 'DO_LOGIN_IN_PROGRESS';
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS';
export const DO_LOGIN_FAILED = 'DO_LOGIN_FAILED';

export const DO_LOGOUT_REQUEST = 'DO_LOGOUT_REQUEST';
export const DO_LOGOUT_IN_PROGRESS = 'DO_LOGOUT_IN_PROGRESS';
export const DO_LOGOUT_SUCCESS = 'DO_LOGOUT_SUCCESS';
export const DO_LOGOUT_FAILED = 'DO_LOGOUT_FAILED';

export const DO_REGISTER_REQUEST = 'DO_REGISTER_REQUEST';
export const DO_REGISTER_IN_PROGRESS = 'DO_REGISTER_IN_PROGRESS';
export const DO_REGISTER_SUCCESS = 'DO_REGISTER_SUCCESS';
export const DO_REGISTER_FAILED = 'DO_REGISTER_FAILED';

export const DO_CONFIRM_USER_REQUEST = 'DO_CONFIRM_USER_REQUEST';
export const DO_CONFIRM_USER_IN_PROGRESS = 'DO_CONFIRM_USER_IN_PROGRESS';
export const DO_CONFIRM_USER_SUCCESS = 'DO_CONFIRM_USER_SUCCESS';
export const DO_CONFIRM_USER_FAILED = 'DO_CONFIRM_USER_FAILED';

export const RESEND_USER_CONFIRMATION_CODE_REQUEST = 'RESEND_USER_CONFIRMATION_CODE_REQUEST';
export const RESEND_USER_CONFIRMATION_CODE_IN_PROGRESS = 'RESEND_USER_CONFIRMATION_CODE_IN_PROGRESS';
export const RESEND_USER_CONFIRMATION_CODE_SUCCESS = 'RESEND_USER_CONFIRMATION_CODE_SUCCESS';
export const RESEND_USER_CONFIRMATION_CODE_FAILED = 'RESEND_USER_CONFIRMATION_CODE_FAILED';

export const SEND_PASSWORD_RESET_CODE_REQUEST = 'SEND_PASSWORD_RESET_CODE_REQUEST';
export const SEND_PASSWORD_RESET_CODE_IN_PROGRESS = 'SEND_PASSWORD_RESET_CODE_IN_PROGRESS';
export const SEND_PASSWORD_RESET_CODE_SUCCESS = 'SEND_PASSWORD_RESET_CODE_SUCCESS';
export const SEND_PASSWORD_RESET_CODE_FAILED = 'SEND_PASSWORD_RESET_CODE_FAILED';

export const DO_RESET_PASSWORD_REQUEST = 'DO_RESET_PASSWORD_REQUEST';
export const DO_RESET_PASSWORD_IN_PROGRESS = 'DO_RESET_PASSWORD_IN_PROGRESS';
export const DO_RESET_PASSWORD_SUCCESS = 'DO_RESET_PASSWORD_SUCCESS';
export const DO_RESET_PASSWORD_FAILED = 'DO_RESET_PASSWORD_FAILED';

export const GET_USER_FL_NAME_REQUEST = 'GET_USER_FL_NAME_REQUEST';
export const GET_USER_FL_NAME_IN_PROGRESS = 'GET_USER_FL_NAME_IN_PROGRESS';
export const GET_USER_FL_NAME_SUCCESS = 'GET_USER_FL_NAME_SUCCESS';
export const GET_USER_FL_NAME_ERROR = 'GET_USER_FL_NAME_ERROR';

export const GET_USER_OTP_NUMBER_REQUEST = 'GET_USER_OTP_NUMBER_REQUEST';

export default {
    DO_LOGIN_REQUEST,
    DO_LOGIN_IN_PROGRESS,
    DO_LOGIN_SUCCESS,
    DO_LOGIN_FAILED,

    DO_LOGOUT_REQUEST,
    DO_LOGOUT_IN_PROGRESS,
    DO_LOGOUT_SUCCESS,
    DO_LOGOUT_FAILED,

    DO_REGISTER_REQUEST,
    DO_REGISTER_IN_PROGRESS,
    DO_REGISTER_SUCCESS,
    DO_REGISTER_FAILED,

    DO_CONFIRM_USER_REQUEST,
    DO_CONFIRM_USER_IN_PROGRESS,
    DO_CONFIRM_USER_SUCCESS,
    DO_CONFIRM_USER_FAILED,

    RESEND_USER_CONFIRMATION_CODE_REQUEST,
    RESEND_USER_CONFIRMATION_CODE_IN_PROGRESS,
    RESEND_USER_CONFIRMATION_CODE_SUCCESS,
    RESEND_USER_CONFIRMATION_CODE_FAILED,

    SEND_PASSWORD_RESET_CODE_REQUEST,
    SEND_PASSWORD_RESET_CODE_IN_PROGRESS,
    SEND_PASSWORD_RESET_CODE_SUCCESS,
    SEND_PASSWORD_RESET_CODE_FAILED,

    DO_RESET_PASSWORD_REQUEST,
    DO_RESET_PASSWORD_IN_PROGRESS,
    DO_RESET_PASSWORD_SUCCESS,
    DO_RESET_PASSWORD_FAILED,

    GET_USER_OTP_NUMBER_REQUEST
};
