export const DO_SAVE_PROPOSAL_FORM = 'DO_SAVE_PROPOSAL_FORM';
export const DO_SAVE_PROPOSAL_FORM_PROGRESS = 'DO_SAVE_PROPOSAL_FORM_PROGRESS';
export const DO_SAVE_PROPOSAL_FORM_SUCCESS = 'DO_SAVE_PROPOSAL_FORM_SUCCESS';
export const DO_SAVE_PROPOSAL_FORM_FAILED = 'DO_SAVE_PROPOSAL_FORM_FAILED';

export const DO_GET_PROPOSAL_FORM = 'DO_GET_PROPOSAL_FORM';
export const DO_GET_PROPOSAL_FORM_PROGRESS = 'DO_GET_PROPOSAL_FORM_PROGRESS';
export const DO_GET_PROPOSAL_FORM_SUCCESS = 'DO_GET_PROPOSAL_FORM_SUCCESS';
export const DO_GET_PROPOSAL_FORM_FAILED = 'DO_GET_PROPOSAL_FORM_FAILED';

export const DO_GET_PROPOSAL_NAMES = 'DO_GET_PROPOSAL_NAMES';
export const DO_GET_PROPOSAL_NAMES_PROGRESS = 'DO_GET_PROPOSAL_NAMES_PROGRESS';
export const DO_GET_PROPOSAL_NAMES_SUCCESS = 'DO_GET_PROPOSAL_NAMES_SUCCESS';
export const DO_GET_PROPOSAL_NAMES_FAILED = 'DO_GET_PROPOSAL_NAMES_FAILED';

export const TAB_KEY_NAME_ASSET = 'Assets';
export const TAB_KEY_ASSET = 'key_assets';

export const TAB_KEY_NAME_LIABILITIES = 'Liabilities';
export const TAB_KEY_LIABILITIES = 'key_liabilities';

export const TAB_KEY_NAME_FUNDING = 'Funding';
export const TAB_KEY_FUNDING = 'key_funding';

export const TAB_KEY_NAME_APPROVAL = 'Approval';
export const TAB_KEY_APPROVAL = 'key_approval';

export default {
    DO_SAVE_PROPOSAL_FORM,
    DO_SAVE_PROPOSAL_FORM_PROGRESS,
    DO_SAVE_PROPOSAL_FORM_SUCCESS,
    DO_SAVE_PROPOSAL_FORM_FAILED,

    DO_GET_PROPOSAL_NAMES,
    DO_GET_PROPOSAL_NAMES_PROGRESS,
    DO_GET_PROPOSAL_NAMES_SUCCESS,
    DO_GET_PROPOSAL_NAMES_FAILED,

    TAB_KEY_NAME_ASSET,
    TAB_KEY_ASSET,
    TAB_KEY_NAME_LIABILITIES,
    TAB_KEY_LIABILITIES,
    TAB_KEY_NAME_FUNDING,
    TAB_KEY_FUNDING,
    TAB_KEY_NAME_APPROVAL,
    TAB_KEY_APPROVAL
};
