export const GET_USER_NOTIFICATIONS_REQUEST = 'GET_USER_NOTIFICATIONS_REQUEST';
export const GET_USER_NOTIFICATIONS_IN_PROGRESS = 'GET_USER_NOTIFICATIONS_IN_PROGRESS';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_FAILED = 'GET_USER_NOTIFICATIONS_FAILED';

export const SET_EMAIL_NOTIFICATIONS_FLAG = 'SET_EMAIL_NOTIFICATIONS_FLAG';
export const SET_EMAIL_NOTIFICATIONS_FLAG_SUCCESS = 'SET_EMAIL_NOTIFICATIONS_FLAG_SUCCESS';

export const UPDATE_LOGGED_USER = 'UPDATE_LOGGED_USER';
export const SET_MARKAS_READ_REQUEST = 'SET_MARKAS_READ_REQUEST';
export const SET_NOTIFICATIONS_MARK_AS_READ_SUCCESS = 'SET_NOTIFICATIONS_MARK_AS_READ_SUCCESS';
export const SET_DELETE_NOTIFICATIONS_REQUEST = 'SET_DELETE_NOTIFICATIONS_REQUEST';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const GET_SEARCH_RESULT_NOTIFICATIONS = 'GET_SEARCH_RESULT_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SEARCH_RESULT_INPROGRESS = 'GET_NOTIFICATIONS_SEARCH_RESULT_INPROGRESS';
export const GET_NOTIFICATIONS_SEARCH_SUCCESS = 'GET_NOTIFICATIONS_SEARCH_SUCCESS';
export const NOTIFICATION_TIMEOUT = 60000;

export const RESET_NOTIFICATION_BELL_RED_DOT = 'RESET_NOTIFICATION_BELL_RED_DOT';
export const RESET_NOTIFICATION_BELL_RED_DOT_IN_PROGRESS = 'RESET_NOTIFICATION_BELL_RED_DOT_IN_PROGRESS';
export const RESET_NOTIFICATION_BELL_RED_DOT_SUCCEESS = 'RESET_NOTIFICATION_BELL_RED_DOT_SUCCEESS';
export const ERROR_OCCURED = 'Error occured.';

export const REQUEST_ARTIFACTS = 'REQUEST_ARTIFACTS';
export const GET_ARTIFACTS_SUCCESS = 'GET_ARTIFACTS_SUCCESS';
export const GET_ARTIFACTS_FAILED = 'GET_ARTIFACTS_FAILED';
