export const SELECT_DOCUMENT_TYPE = 'Select document type';
export const SELECT_DOCUMENT_NAME = 'Select document name';
export const NO_DATA = '-- No documents available --';

export const GET_REPORT_DATA_REQUEST = 'GET_REPORT_DATA_REQUEST';
export const GET_REPORT_DATA_INPROGRESS = 'GET_REPORT_DATA_INPROGRESS';
export const GET_REPORT_DATA_SUCCESS = 'GET_REPORT_DATA_SUCCESS';
export const GET_REPORT_DATA_FAILED = 'GET_REPORT_DATA_FAILED';

export const GET_SELECTED_REPORT_DATA_REQUEST = 'GET_SELECTED_REPORT_DATA_REQUEST';
export const GET_SELECTED_REPORT_DATA_INPROGRESS = 'GET_SELECTED_REPORT_DATA_INPROGRESS';
export const GET_SELECTED_REPORT_DATA_SUCCESS = 'GET_SELECTED_REPORT_DATA_SUCCESS';
export const GET_SELECTED_REPORT_DATA_FAILED = 'GET_SELECTED_REPORT_DATA_FAILED';
