export const GET_REPORT_TYPES = 'GET_REPORT_TYPES';
export const GET_REPORT_TYPES_SUCCESS = 'GET_REPORT_TYPES_SUCCESS';
export const GET_REPORT_TYPES_ERROR = 'GET_REPORT_TYPES_ERROR';

export const GET_UPLOAD_REPORT_SCHEME = 'GET_UPLOAD_REPORT_SCHEME';
export const GET_UPLOAD_REPORT_SCHEME_SUCCESS = 'GET_UPLOAD_REPORT_SCHEME_SUCCESS';
export const GET_UPLOAD_REPORT_SCHEME_ERROR = 'GET_UPLOAD_REPORT_SCHEME_ERROR';

export const GET_GENERATE_REPORT_SCHEME = 'GET_GENERATE_REPORT_SCHEME';
export const GET_GENERATE_REPORT_SCHEME_SUCCESS = 'GET_GENERATE_REPORT_SCHEME_SUCCESS';
export const GET_GENERATE_REPORT_SCHEME_ERROR = 'GET_GENERATE_REPORT_SCHEME_ERROR';


export const GET_REPORT_UPLOAD_URL = 'GET_REPORT_UPLOAD_URL';
export const GET_REPORT_UPLOAD_URL_SUCCESS = 'GET_REPORT_UPLOAD_URL_SUCCESS';
export const GET_REPORT_UPLOAD_URL_ERROR = 'GET_REPORT_UPLOAD_URL_ERROR';

export const SET_UPLOADED_REPORTS = 'SET_UPLOADED_REPORTS';
export const RESET_UPLOADED_REPORTS = 'RESET_UPLOADED_REPORTS';


export const GENERATE_REPORT_VALIDATION_REQUEST = 'GENERATE_REPORT_VALIDATION_REQUEST';
export const GENERATE_REPORT_VALIDATION_SUCCESS = 'GENERATE_REPORT_VALIDATION_SUCCESS';
export const GENERATE_REPORT_VALIDATION_ERROR = 'GENERATE_REPORT_VALIDATION_ERROR';

export const GENERATE_REPORT_REQUEST = 'GENERATE_REPORT_REQUEST';
export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS';
export const GENERATE_REPORT_ERROR = 'GENERATE_REPORT_ERROR';

export const GENERATE_REPORT_SUCCESS_RESET = 'GENERATE_REPORT_SUCCESS_RESET';
