export const SET_NOTIFICATINS_CONFIG_REQUEST = 'SET_NOTIFICATINS_CONFIG_REQUEST';
export const SET_NOTIFICATINS_CONFIG_SUCCESS = 'SET_NOTIFICATINS_CONFIG_SUCCESS';
export const SET_NOTIFICATINS_CONFIG_ERROR = 'SET_NOTIFICATINS_CONFIG_ERROR';
