export const GET_KEY_METRICS_CONFIG_REQUEST = 'GET_KEY_METRICS_CONFIG_REQUEST';
export const GET_KEY_METRICS_CONFIG_IN_PROGRESS = 'GET_KEY_METRICS_CONFIG_IN_PROGRESS';
export const GET_KEY_METRICS_CONFIG_SUCCESS = 'GET_KEY_METRICS_CONFIG_SUCCESS';
export const GET_KEY_METRICS_CONFIG_FAILED = 'GET_KEY_METRICS_CONFIG_FAILED';

export const FILTER_SCHEMES_REQUEST = 'FILTER_SCHEMES_REQUEST';
export const FILTER_SCHEMES_IN_PROGRESS = 'FILTER_SCHEMES_IN_PROGRESS';
export const FILTER_SCHEMES_SUCCESS = 'FILTER_SCHEMES_SUCCESS';
export const FILTER_SCHEMES_FAILED = 'FILTER_SCHEMES_FAILED';

export const GET_MY_VIEWS_REQUEST = 'GET_MY_VIEWS_REQUEST';
export const GET_MY_VIEWS_IN_PROGRESS = 'GET_MY_VIEWS_IN_PROGRESS';
export const GET_MY_VIEWS_SUCCESS = 'GET_MY_VIEWS_SUCCESS';
export const GET_MY_VIEWS_FAILED = 'GET_MY_VIEWS_FAILED';

export const DELETE_VIEW_REQUEST = 'DELETE_VIEW_REQUEST';
export const DELETE_VIEW_IN_PROGRESS = 'DELETE_VIEW_IN_PROGRESS';
export const DELETE_VIEW_SUCCESS = 'DELETE_VIEW_SUCCESS';
export const DELETE_VIEW_FAILED = 'DELETE_VIEW_FAILED';

export const SAVE_VIEW_REQUEST = 'SAVE_VIEW_REQUEST';
export const SAVE_VIEW_IN_PROGRESS = 'SAVE_VIEW_IN_PROGRESS';
export const SAVE_VIEW_SUCCESS = 'SAVE_VIEW_SUCCESS';
export const SAVE_VIEW_FAILED = 'SAVE_VIEW_FAILED';

export const UPDATE_VIEW_REQUEST = 'UPDATE_VIEW_REQUEST';
export const UPDATE_VIEW_IN_PROGRESS = 'UPDATE_VIEW_IN_PROGRESS';
export const UPDATE_VIEW_SUCCESS = 'UPDATE_VIEW_SUCCESS';
export const UPDATE_VIEW_FAILED = 'UPDATE_VIEW_FAILED';

export const EDIT_VIEW_REQUEST = 'EDIT_VIEW_REQUEST';
export const EDIT_VIEW_IN_PROGRESS = 'EDIT_VIEW_IN_PROGRESS';
export const EDIT_VIEW_SUCCESS = 'EDIT_VIEW_SUCCESS';
export const EDIT_VIEW_FAILED = 'EDIT_VIEW_FAILED';

export const SCHEME_DATA_CHANGE_REQUEST = 'SCHEME_DATA_CHANGE_REQUEST';
export const SCHEME_DATA_CHANGE_IN_PROGRESS = 'SCHEME_DATA_CHANGE_IN_PROGRESS';
export const SCHEME_DATA_CHANGE_SUCCESS = 'SCHEME_DATA_CHANGE_SUCCESS';
export const SCHEME_DATA_CHANGE_FAILED = 'SCHEME_DATA_CHANGE_FAILED';

export const SAVE_GLOBAL_VIEW_REQUEST = 'SAVE_GLOBAL_VIEW_REQUEST';
export const SAVE_GLOBAL_VIEW_IN_PROGRESS = 'SAVE_GLOBAL_VIEW_IN_PROGRESS';
export const SAVE_GLOBAL_VIEW_SUCCESS = 'SAVE_GLOBAL_VIEW_SUCCESS';
export const SAVE_GLOBAL_VIEW_FAILED = 'SAVE_GLOBAL_VIEW_FAILED';

export const UPDATE_GLOBAL_VIEW_REQUEST = 'UPDATE_GLOBAL_VIEW_REQUEST';
export const UPDATE_GLOBAL_VIEW_IN_PROGRESS = 'UPDATE_GLOBAL_VIEW_IN_PROGRESS';
export const UPDATE_GLOBAL_VIEW_SUCCESS = 'UPDATE_GLOBAL_VIEW_SUCCESS';
export const UPDATE_GLOBAL_VIEW_FAILED = 'UPDATE_GLOBAL_VIEW_FAILED';

export const EDIT_GLOBAL_VIEW_REQUEST = 'EDIT_GLOBAL_VIEW_REQUEST';
export const EDIT_GLOBAL_VIEW_IN_PROGRESS = 'EDIT_GLOBAL_VIEW_IN_PROGRESS';
export const EDIT_GLOBAL_VIEW_SUCCESS = 'EDIT_GLOBAL_VIEW_SUCCESS';
export const EDIT_GLOBAL_VIEW_FAILED = 'EDIT_GLOBAL_VIEW_FAILED';

export const DELETE_GLOBAL_VIEW_REQUEST = 'DELETE_GLOBAL_VIEW_REQUEST';
export const DELETE_GLOBAL_VIEW_IN_PROGRESS = 'DELETE_GLOBAL_VIEW_IN_PROGRESS';
export const DELETE_GLOBAL_VIEW_SUCCESS = 'DELETE_GLOBAL_VIEW_SUCCESS';
export const DELETE_GLOBAL_VIEW_FAILED = 'DELETE_GLOBAL_VIEW_FAILED';

export const GET_MY_DEFAULT_ORG_GROUPS_REQUEST = 'GET_MY_DEFAULT_ORG_GROUPS_REQUEST';
export const GET_MY_DEFAULT_ORG_GROUPS_IN_PROGRESS = 'GET_MY_DEFAULT_ORG_GROUPS_IN_PROGRESS';
export const GET_MY_DEFAULT_ORG_GROUPS_SUCCESS = 'GET_MY_DEFAULT_ORG_GROUPS_SUCCESS';
export const GET_MY_DEFAULT_ORG_GROUPS_FAILED = 'GET_MY_DEFAULT_ORG_GROUPS_FAILED';

export const GET_MY_CURRENT_APPLIED_VIEW_REQUEST = 'GET_MY_CURRENT_APPLIED_VIEW_REQUEST';
export const GET_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS = 'GET_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS';
export const GET_MY_CURRENT_APPLIED_VIEW_SUCCESS = 'GET_MY_CURRENT_APPLIED_VIEW_SUCCESS';
export const GET_MY_CURRENT_APPLIED_VIEW_FAILED = 'GET_MY_CURRENT_APPLIED_VIEW_FAILED';

export const SAVE_MY_CURRENT_APPLIED_VIEW_REQUEST = 'SAVE_MY_CURRENT_APPLIED_VIEW_REQUEST';
export const SAVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS = 'SAVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS';
export const SAVE_MY_CURRENT_APPLIED_VIEW_SUCCESS = 'SAVE_MY_CURRENT_APPLIED_VIEW_SUCCESS';
export const SAVE_MY_CURRENT_APPLIED_VIEW_FAILED = 'SAVE_MY_CURRENT_APPLIED_VIEW_FAILED';

export const REMOVE_MY_CURRENT_APPLIED_VIEW_REQUEST = 'REMOVE_MY_CURRENT_APPLIED_VIEW_REQUEST';
export const REMOVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS = 'REMOVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS';
export const REMOVE_MY_CURRENT_APPLIED_VIEW_SUCCESS = 'REMOVE_MY_CURRENT_APPLIED_VIEW_SUCCESS';
export const REMOVE_MY_CURRENT_APPLIED_VIEW_FAILED = 'REMOVE_MY_CURRENT_APPLIED_VIEW_FAILED';

export default {
    GET_KEY_METRICS_CONFIG_REQUEST,
    GET_KEY_METRICS_CONFIG_IN_PROGRESS,
    GET_KEY_METRICS_CONFIG_SUCCESS,
    GET_KEY_METRICS_CONFIG_FAILED,

    FILTER_SCHEMES_REQUEST,
    FILTER_SCHEMES_IN_PROGRESS,
    FILTER_SCHEMES_SUCCESS,
    FILTER_SCHEMES_FAILED,

    GET_MY_VIEWS_REQUEST,
    GET_MY_VIEWS_IN_PROGRESS,
    GET_MY_VIEWS_SUCCESS,
    GET_MY_VIEWS_FAILED,

    DELETE_VIEW_REQUEST,
    DELETE_VIEW_IN_PROGRESS,
    DELETE_VIEW_SUCCESS,
    DELETE_VIEW_FAILED,

    SAVE_VIEW_REQUEST,
    SAVE_VIEW_IN_PROGRESS,
    SAVE_VIEW_SUCCESS,
    SAVE_VIEW_FAILED,

    UPDATE_VIEW_REQUEST,
    UPDATE_VIEW_IN_PROGRESS,
    UPDATE_VIEW_SUCCESS,
    UPDATE_VIEW_FAILED,

    EDIT_VIEW_REQUEST,
    EDIT_VIEW_IN_PROGRESS,
    EDIT_VIEW_SUCCESS,
    EDIT_VIEW_FAILED,

    SCHEME_DATA_CHANGE_REQUEST,
    SCHEME_DATA_CHANGE_IN_PROGRESS,
    SCHEME_DATA_CHANGE_SUCCESS,
    SCHEME_DATA_CHANGE_FAILED,

    SAVE_GLOBAL_VIEW_REQUEST,
    SAVE_GLOBAL_VIEW_IN_PROGRESS,
    SAVE_GLOBAL_VIEW_SUCCESS,
    SAVE_GLOBAL_VIEW_FAILED,

    UPDATE_GLOBAL_VIEW_REQUEST,
    UPDATE_GLOBAL_VIEW_IN_PROGRESS,
    UPDATE_GLOBAL_VIEW_SUCCESS,
    UPDATE_GLOBAL_VIEW_FAILED,

    EDIT_GLOBAL_VIEW_REQUEST,
    EDIT_GLOBAL_VIEW_IN_PROGRESS,
    EDIT_GLOBAL_VIEW_SUCCESS,
    EDIT_GLOBAL_VIEW_FAILED,

    DELETE_GLOBAL_VIEW_REQUEST,
    DELETE_GLOBAL_VIEW_IN_PROGRESS,
    DELETE_GLOBAL_VIEW_SUCCESS,
    DELETE_GLOBAL_VIEW_FAILED,

    GET_MY_DEFAULT_ORG_GROUPS_REQUEST,
    GET_MY_DEFAULT_ORG_GROUPS_IN_PROGRESS,
    GET_MY_DEFAULT_ORG_GROUPS_SUCCESS,
    GET_MY_DEFAULT_ORG_GROUPS_FAILED,

    GET_MY_CURRENT_APPLIED_VIEW_REQUEST,
    GET_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS,
    GET_MY_CURRENT_APPLIED_VIEW_SUCCESS,
    GET_MY_CURRENT_APPLIED_VIEW_FAILED,

    SAVE_MY_CURRENT_APPLIED_VIEW_REQUEST,
    SAVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS,
    SAVE_MY_CURRENT_APPLIED_VIEW_SUCCESS,
    SAVE_MY_CURRENT_APPLIED_VIEW_FAILED,

    REMOVE_MY_CURRENT_APPLIED_VIEW_REQUEST,
    REMOVE_MY_CURRENT_APPLIED_VIEW_IN_PROGRESS,
    REMOVE_MY_CURRENT_APPLIED_VIEW_SUCCESS,
    REMOVE_MY_CURRENT_APPLIED_VIEW_FAILED
};
