export const GET_ASSIGN_USER_LIST = 'GET_ASSIGN_USER_LIST';
export const GET_ASSIGN_USER_LIST_IN_PROGRESS = 'GET_ASSIGN_USER_LIST_IN_PROGRESS';
export const GET_ASSIGN_USER_LIST_SUCCESS = 'GET_ASSIGN_USER_LIST_SUCCESS';
export const GET_ASSIGN_USER_LIST_FAILED = 'GET_ASSIGN_USER_LIST_FAILED';
export const UPDATE_ASSIGN_USER = 'UPDATE_ASSIGN_USER';
